services:
  mysql:
    image: mysql:8.0
    container_name: mysql_smartbus
    environment:
      MYSQL_ROOT_PASSWORD: smartbus123
      MYSQL_DATABASE: smart_bus
      TZ: America/Sao_Paulo
    command: --default-time-zone='America/Sao_Paulo'
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: